{
  "language": "ruby",
  "rvm": "2.2.2",
  "env": "DB=mysql",
  "script": [
    "RAILS_ENV=test bundle exec rake db:migrate --trace",
    "bundle exec rspec spec/models/",
    "bundle exec rspec spec/controllers/",
    "bundle exec rspec spec/features/",
    "bundle exec rspec spec/routing/"
  ],
  "before_script": [
    "mysql -e 'create database myapp_test'"
  ],
  "bundler_args": "--binstubs=./bundler_stubs",
  "test": {
    "adapter": "mysql2",
    "database": "myapp_test",
    "username": "travis",
    "encoding": "utf8"
  },
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
