#File che contiene variabili d'ambiente.

#Variabili email
GMAIL_USERNAME: 'gaaloorg@gmail.com'
GMAIL_PASSWORD: 'Retrobode53'

#Variabili paypal
PAYPAL_CLIENT_ID: EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
PAYPAL_CLIENT_SECRET: EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM
PAYPAL_APP_ID: APP-80W284485P519543T
PAYPAL_USERNAME: jb-us-seller_api1.paypal.com
PAYPAL_PASSWORD: WX4WTU3S8MY44S7F
PAYPAL_SIGNATURE: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy

#Variabili Google API
#Vecchia -> GOOGLE_API_KEY: AIzaSyBzvisYtIWdt5PVvyiRkBdkVCvD2QIPJZY
GOOGLE_API_KEY: AIzaSyAgJqdwLDks1CO1V0Jt136pklDWbM1ewVk 
