# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7cede5661c615446e91cdf1e2427493c35d1f0e41cc017f7aa984e3db122fa31863bb17e2d1654a3249dfeb8fe3fd13dede1e1412fbc41a21ab58f42dd9f82ed

test:
  secret_key_base: 16e71a024df1a76f846e8f6c3142a0ece65abcd34e0082923c61e53c26416e2c18d7895b296b936f383afc7bbf31b3aace457a3a62672d1dda7600ef1b41b664

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  #Variabili email
  GMAIL_USERNAME: 'inserire email'
  GMAIL_PASSWORD: 'inserire password email'

  #Variabili paypal
  PAYPAL_CLIENT_ID: inserire id cliente generato da api paypal
  PAYPAL_CLIENT_SECRET: inserire secret cliente generato da api paypal
  PAYPAL_APP_ID: inserire paypal app id generato da api paypal
  PAYPAL_USERNAME: inserire paypal username generato da api paypal
  PAYPAL_PASSWORD: inserire password paypal generato da api paypal
  PAYPAL_SIGNATURE: inserire signature paypal generato da api paypal

  #Variabili Google API
  GOOGLE_API_KEY: <%= ENV["GOOGLE_API_KEY"] %>
