Polo.create(nome: 'AP Messina')
Polo.create(nome: 'AP Palermo')
Polo.create(nome: 'AP Catania Buuu')

Citta.create(nome: 'Messina', provincia: 'Messina', regione: 'Sicilia', polo_id: 1)
Citta.create(nome: 'Palermo', provincia: 'Messina', regione: 'Sicilia', polo_id: 2)
Citta.create(nome: 'Catania Buuu', provincia: 'Messina', regione: 'Sicilia', polo_id: 3)

Indirizzo.create(via: 'Via delle Vie', ncivico: 1, cap: '00110', quartiere: 'scampia', citta_id: 1)
Indirizzo.create(via: 'Via dei viottoli', ncivico: 1, cap: '00110', quartiere: 'scampia', citta_id: 1)
Indirizzo.create(via: 'Contrada della morte', ncivico: 13, cap: '00110', quartiere: 'scampia', citta_id: 1)
Indirizzo.create(via: 'Via dalle palle', ncivico: 21, cap: '00110', quartiere: 'Boschi', citta_id:2)
Indirizzo.create(via: 'Largo e stretto', ncivico: 61, cap: '00110', quartiere: 'Boschi', citta_id:2)
Indirizzo.create(via: 'Via della Gggente', ncivico: 21, cap: '00110', quartiere: 'Boschi', citta_id:2)
Indirizzo.create(via: 'Via del kaffeeee', ncivico: 1, cap: '00110', quartiere: 'Oceano', citta_id: 3)
Indirizzo.create(via: 'Via Silvio Berlusconi', ncivico: 1, cap: '00110', quartiere: 'Oceano', citta_id: 3)
Indirizzo.create(via: 'Via Matteo Renzi', ncivico: 81, cap: '00110', quartiere: 'Oceano', citta_id: 3)
Indirizzo.create(via: 'Via da qui', ncivico: 11, cap: '00110', quartiere: 'Oceano', citta_id: 3)
Indirizzo.create(via: 'Via del mondo', ncivico: 12, cap: '00110', quartiere: 'Oceano', citta_id: 3)

Categoria.create(nome: 'Alimentari')
Categoria.create(nome: 'Divertimento')
Categoria.create(nome: 'Agraria')
Categoria.create(nome: 'Vacanze')
Categoria.create(nome: 'Bricolage')
Categoria.create(nome: 'Cucina')
Categoria.create(nome: 'Omicidi')
Categoria.create(nome: 'Sanitari')
Categoria.create(nome: 'Intrattenimento')

Sottocategoria.create(nome: 'Ristoranti', categoria_id: 1)
Sottocategoria.create(nome: 'Palestre', categoria_id: 1)
Sottocategoria.create(nome: 'Agenzie di Viaggio', categoria_id: 2)
Sottocategoria.create(nome: 'Accademie della crusca', categoria_id: 3)
Sottocategoria.create(nome: 'Pollifici', categoria_id: 4)
Sottocategoria.create(nome: 'Carceri', categoria_id: 5)
Sottocategoria.create(nome: 'Fazzoletterie', categoria_id: 6)
Sottocategoria.create(nome: 'Fiorai', categoria_id: 7)
Sottocategoria.create(nome: 'Farmacie', categoria_id: 8)
Sottocategoria.create(nome: 'Cellularerie', categoria_id: 9)

Admin.create(email: 'gab@riele.com', password: '123456', password_confirmation: '123456', polo_id: 1)
Admin.create(email: 'lor@enzo.com', password: '1q2w3e', password_confirmation: '1q2w3e', polo_id: 2)
Admin.create(email: 'alex@email.it', password: 'password', password_confirmation: 'password', polo_id: 3)

Cliente.create(nome: 'Gigi', cognome: 'Meraviglia', email: 'cli1@ente.it', password: '123456', password_confirmation: '123456',indirizzo_id: 1)
Cliente.create(nome: 'Rino', cognome: 'Rino', email: 'cli2@ente.it', password: '123456', password_confirmation: '123456',indirizzo_id: 2)
Cliente.create(nome: 'Franco', cognome: 'Massimo', email: 'cli3@ente.it', password: '123456', password_confirmation: '123456',indirizzo_id: 3)
Cliente.create(nome: 'Tommaso', cognome: 'Meraviglia', email: 'cli4@ente.it', password: '123456', password_confirmation: '123456',indirizzo_id: 4)
Cliente.create(nome: 'Massimo', cognome: 'Franco', email: 'cli5@ente.it', password: '123456', password_confirmation: '123456',indirizzo_id: 5)

Titolare.create(nome: 'Tito', cognome: 'Lare', email: 'tito1@lare.it', password: '123456', password_confirmation: '123456',indirizzo_id: 6)
Titolare.create(nome: 'Giangiovanni', cognome: 'Itto', email: 'tito2@lare.it', password: '123456', password_confirmation: '123456',indirizzo_id: 7)
Titolare.create(nome: 'Mimmo', cognome: 'Trippa', email: 'tito3@lare.it', password: '123456', password_confirmation: '123456',indirizzo_id: 8)
Titolare.create(nome: 'Edoardo', cognome: 'Dei Boschi', email: 'tito4@lare.it', password: '123456', password_confirmation: '123456',indirizzo_id: 9)
Titolare.create(nome: 'Dio', cognome: 'Bello', email: 'tito5@lare.it', password: '123456', password_confirmation: '123456',indirizzo_id: 10)

Impresa.create(nome: 'La Cozza Felice', titolare_id: 1, citta_id: 1)
Impresa.create(nome: 'Ristorante La Minestra Riscaldata', titolare_id: 1, citta_id: 1)
Impresa.create(nome: 'Profumeria dal Lercio', titolare_id: 2, citta_id: 2)
Impresa.create(nome: 'Tabacchi & AK-47', titolare_id: 3,citta_id: 1)
Impresa.create(nome: 'Ricatti per la casa', titolare_id: 3, citta_id: 1)
Impresa.create(nome: 'Panineria del tosto', titolare_id: 3, citta_id: 3)
Impresa.create(nome: 'Viaggi in Messico srl', titolare_id: 4, citta_id: 3)
Impresa.create(nome: 'Stalker solitari', titolare_id: 5, citta_id: 3)

Prodotto.create(nome:'Minestra di cozze', prezzo: 50, qta: 10, impresa_id: 1)
Prodotto.create(nome:'Salami in salamoia', prezzo: 10, qta: 140, impresa_id: 2)
Prodotto.create(nome:'Zucchine scadute', prezzo: 1, qta: 20, impresa_id: 2)
Prodotto.create(nome:'Eau de autogrill', prezzo: 200, qta: 100, impresa_id: 3)
Prodotto.create(nome:'Acqua di Gianni', prezzo: 10000, qta: 1, impresa_id: 3)
Prodotto.create(nome:'Sigarette furbe', prezzo: 5, qta: 50, impresa_id: 4)
Prodotto.create(nome:'Lavapanni', prezzo: 20, qta: 3, impresa_id: 5)
Prodotto.create(nome:'Panino alla carbonara', prezzo: 30, qta: 60, impresa_id: 6)
Prodotto.create(nome:'Boeing 747', prezzo: 3445540, qta: 60, impresa_id: 7)
Prodotto.create(nome:'Aeroplano senza ali', prezzo: 100000, qta: 60, impresa_id: 7)

Ordine.create(stato: 'spedito', cliente_id: 1, impresa_id: 1)
Ordine.create(stato: 'spedito', cliente_id: 1, impresa_id: 2)
Ordine.create(stato: 'in attesa di pagamento', cliente_id: 4, impresa_id: 3)
Ordine.create(stato: 'in attesa di pagamento', cliente_id: 2, impresa_id: 7)
Ordine.create(stato: 'ricevuto', cliente_id: 5, impresa_id: 4)

Prodotto.find(1).ordini << Ordine.find(1)
Prodotto.find(2).ordini << Ordine.find(1)
Prodotto.find(3).ordini << Ordine.find(2)
Prodotto.find(4).ordini << Ordine.find(3)
Prodotto.find(5).ordini << Ordine.find(4)
Prodotto.find(5).ordini << Ordine.find(5)
Prodotto.find(6).ordini << Ordine.find(5)
