# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#TODO: riadattare il file di seeds alle validations introdotte

Polo.create(nome: 'AP Messina').save(validate: false)
Polo.create(nome: 'AP Palermo').save(validate: false)
Polo.create(nome: 'AP Catania Buuu').save(validate: false)

Citta.create(nome: 'Messina', provincia: 'Messina', regione: 'Sicilia', polo_id: 1)
Citta.create(nome: 'Palermo', provincia: 'Palermo', regione: 'Sicilia', polo_id: 2)
Citta.create(nome: 'Catania Buuu', provincia: 'Catania Buuu', regione: 'Sicilia', polo_id: 3)


Categoria.create(nome: 'Alimentari')
Categoria.create(nome: 'Divertimento')
Categoria.create(nome: 'Agraria')
Categoria.create(nome: 'Vacanze')
Categoria.create(nome: 'Bricolage')
Categoria.create(nome: 'Cucina')
Categoria.create(nome: 'Omicidi')
Categoria.create(nome: 'Sanitari')
Categoria.create(nome: 'Intrattenimento')

Sottocategoria.create(nome: 'Ristoranti', categoria_id: 1)
Sottocategoria.create(nome: 'Palestre', categoria_id: 1)
Sottocategoria.create(nome: 'Agenzie di Viaggio', categoria_id: 2)
Sottocategoria.create(nome: 'Accademie della crusca', categoria_id: 3)
Sottocategoria.create(nome: 'Pollifici', categoria_id: 4)
Sottocategoria.create(nome: 'Carceri', categoria_id: 5)
Sottocategoria.create(nome: 'Fazzoletterie', categoria_id: 6)
Sottocategoria.create(nome: 'Fiorai', categoria_id: 7)
Sottocategoria.create(nome: 'Farmacie', categoria_id: 8)
Sottocategoria.create(nome: 'Cellularerie', categoria_id: 9)

Admin.create(email: 'gab@riele.com', password: '123456', password_confirmation: '123456', polo_id: 1)
Admin.create(email: 'lor@enzo.com', password: '1q2w3e', password_confirmation: '1q2w3e', polo_id: 2)
Admin.create(email: 'alex@email.it', password: 'password', password_confirmation: 'password', polo_id: 3)

Cliente.create(nome: 'Gigi', cognome: 'Meraviglia', cf: 'ajsjsan', telefono: '12345', data_nascita: Date.parse('08/08/1964'), email: 'cli1@ente.it', password: '123456', password_confirmation: '123456')
Cliente.create(nome: 'Rino', cognome: 'Rino', cf: 'dsahju', telefono: '1354', data_nascita: Date.parse('04/11/1991'), email: 'cli2@ente.it', password: '123456', password_confirmation: '123456')
Cliente.create(nome: 'Franco', cognome: 'Massimo', cf: 'jasdnjd', telefono: '15325', data_nascita: Date.parse('01/01/1992'), email: 'cli3@ente.it', password: '123456', password_confirmation: '123456')
Cliente.create(nome: 'Tommaso', cognome: 'Meraviglia', cf: 'skanjd', telefono: '1242', data_nascita: Date.parse('03/05/1907'), email: 'cli4@ente.it', password: '123456', password_confirmation: '123456')
Cliente.create(nome: 'Massimo', cognome: 'Franco', cf: 'sdakcc', telefono: '15252', data_nascita: Date.parse('01/05/1930'), email: 'cli5@ente.it', password: '123456', password_confirmation: '123456')

Titolare.create(nome: 'Tito', cognome: 'Lare', email: 'tito1@lare.it', password: '123456', password_confirmation: '123456', telefono: '3423556', data_nascita: Date.parse('01/05/1930'), cf: 'sdgsg')
Titolare.create(nome: 'Giangiovanni', cognome: 'Itto', email: 'tito2@lare.it', password: '123456', password_confirmation: '123456', telefono: '73249', data_nascita: Date.parse('09/06/1955'), cf: 'kfmkimke')
Titolare.create(nome: 'Mimmo', cognome: 'Trippa', email: 'tito3@lare.it', password: '123456', password_confirmation: '123456', telefono: '000222', data_nascita: Date.parse('03/05/1907'), cf: 'einjnf')
Titolare.create(nome: 'Edoardo', cognome: 'Dei Boschi', email: 'tito4@lare.it', password: '123456', password_confirmation: '123456', telefono: '634622', data_nascita: Date.parse('04/11/1991'), cf: 'ijgin')
Titolare.create(nome: 'Dio', cognome: 'Bello', email: 'tito5@lare.it', password: '123456', password_confirmation: '123456', telefono: '987765654', data_nascita: Date.parse('08/08/1964'), cf: 'wefjun')

Impresa.create(nome: 'La Cozza Felice', telefono: '32224', descrizione: 'Cozze belle', titolare_id: 1, citta_id: 1, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Ristorante La Minestra Riscaldata', telefono: '31331', descrizione: 'Minestre belle', titolare_id: 1, citta_id: 1, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Profumeria dal Lercio', telefono: '6564', descrizione: 'Profumi belli', titolare_id: 2, citta_id: 2, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Tabacchi & AK-47', telefono: '523221', descrizione: 'Tabacchi belli', titolare_id: 3,citta_id: 1, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Ricatti per la casa', telefono: '878787', descrizione: 'Ricatti belli', titolare_id: 3, citta_id: 1, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Panineria del tosto', telefono: '4354354', descrizione: 'Panini belli', titolare_id: 3, citta_id: 2, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Viaggi in Messico srl', telefono: '543522', descrizione: 'Viaggi belli', titolare_id: 4, citta_id: 2, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Calcolatrici Ipotetiche', telefono: '355221', descrizione: 'Calcoli belli', titolare_id: 3, citta_id: 2, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Stiamoci Male & co.', telefono: '777555', descrizione: 'Male belli', titolare_id: 5, citta_id: 3, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'Non siamo mafiosi, fidati SPA', telefono: '88554', descrizione: 'Mafiosi belli', titolare_id: 2, citta_id: 3, verificato: true, congelato: false).save(validate: false)
Impresa.create(nome: 'We uagliò bell stu orologgg', telefono: '36636', descrizione: 'Orolog belli', titolare_id: 4, citta_id: 3, verificato: true, congelato: true).save(validate: false) #TODO: assegnare ordine

Prodotto.create(nome:'Minestra di cozze', prezzo: 50, qta: 10, descrizione: 'Minestra bella', impresa_id: 1)
Prodotto.create(nome:'Salami in salamoia', prezzo: 10, qta: 140, descrizione: 'Salami belli', impresa_id: 2)
Prodotto.create(nome:'Zucchine scadute', prezzo: 1, qta: 20, descrizione: 'Zucchine belle', impresa_id: 2)
Prodotto.create(nome:'Eau de autogrill', prezzo: 200, qta: 100, descrizione: 'Profumo bello', impresa_id: 3)
Prodotto.create(nome:'Acqua di Gianni', prezzo: 10000, qta: 1, descrizione: 'Acqua bella', impresa_id: 3)
Prodotto.create(nome:'Sigarette furbe', prezzo: 5, qta: 50, descrizione: 'Sigarette belle', impresa_id: 4)
Prodotto.create(nome:'Lavapanni', prezzo: 20, qta: 3, descrizione: 'Lavapanni belli', impresa_id: 5)
Prodotto.create(nome:'Panino alla carbonara', prezzo: 30, qta: 60, descrizione: 'Carbonare belle', impresa_id: 6)
Prodotto.create(nome:'Boeing 747', prezzo: 3445540, qta: 60, descrizione: 'Boeing belli', impresa_id: 7)
Prodotto.create(nome:'Aeroplano senza ali', prezzo: 100000, descrizione: 'Aerei belli', qta: 60, impresa_id: 7)

StatoOrdine.create(stato: 'In attesa')
StatoOrdine.create(stato: 'Pagato')
StatoOrdine.create(stato: 'Spedito')
StatoOrdine.create(stato: 'Ricevuto')

Ordine.create(cliente_id: 1, impresa_id: 1, stato_ordine_id: 1).save(validate: false)
Ordine.create(cliente_id: 1, impresa_id: 2, stato_ordine_id: 1).save(validate: false)
Ordine.create(cliente_id: 4, impresa_id: 3, stato_ordine_id: 1).save(validate: false)
Ordine.create(cliente_id: 2, impresa_id: 7, stato_ordine_id: 1).save(validate: false)
Ordine.create(cliente_id: 5, impresa_id: 4, stato_ordine_id: 2).save(validate: false)
Ordine.create(cliente_id: 5, impresa_id: 5, stato_ordine_id: 2).save(validate: false)
Ordine.create(cliente_id: 3, impresa_id: 4, stato_ordine_id: 2).save(validate: false)
Ordine.create(cliente_id: 4, impresa_id: 4, stato_ordine_id: 3).save(validate: false)
Ordine.create(cliente_id: 5, impresa_id: 6, stato_ordine_id: 4).save(validate: false)

Prodotto.find(1).ordini << Ordine.find(1)
Prodotto.find(2).ordini << Ordine.find(2)
Prodotto.find(3).ordini << Ordine.find(2)
Prodotto.find(4).ordini << Ordine.find(3)
Prodotto.find(9).ordini << Ordine.find(4)
Prodotto.find(6).ordini << Ordine.find(5)
Prodotto.find(6).ordini << Ordine.find(5)
Prodotto.find(7).ordini << Ordine.find(6)
Prodotto.find(6).ordini << Ordine.find(7)
Prodotto.find(6).ordini << Ordine.find(7)
Prodotto.find(6).ordini << Ordine.find(8)
Prodotto.find(8).ordini << Ordine.find(9)

Impresa.find(1).sottocategorie << Sottocategoria.find(1)
Impresa.find(1).sottocategorie << Sottocategoria.find(5)
Impresa.find(1).sottocategorie << Sottocategoria.find(2)
Impresa.find(2).sottocategorie << Sottocategoria.find(6)
Impresa.find(3).sottocategorie << Sottocategoria.find(4)
Impresa.find(3).sottocategorie << Sottocategoria.find(9)
Impresa.find(4).sottocategorie << Sottocategoria.find(10)
Impresa.find(5).sottocategorie << Sottocategoria.find(2)
Impresa.find(5).sottocategorie << Sottocategoria.find(3)
Impresa.find(5).sottocategorie << Sottocategoria.find(7)
Impresa.find(6).sottocategorie << Sottocategoria.find(3)
Impresa.find(6).sottocategorie << Sottocategoria.find(2)
Impresa.find(7).sottocategorie << Sottocategoria.find(1)
Impresa.find(7).sottocategorie << Sottocategoria.find(8)
Impresa.find(8).sottocategorie << Sottocategoria.find(4)
